/* CVS $Id: $ */
package de.jhs.oldenburg.gg.rdf.vocabulary; 
import org.apache.jena.rdf.model.*;
import org.apache.jena.ontology.*;
 
/**
 * Vocabulary definitions from file:C:\Users\Philipp\git\Project-TripleStoreDataBase\Schemagen4GG\src/main/vocabs/friends.owl 
 * @author Auto-generated by schemagen on 28 Dez 2016 20:57 
 */
public class Friends {
    /** <p>The ontology model that holds the vocabulary terms</p> */
    private static OntModel m_model = ModelFactory.createOntologyModel( OntModelSpec.OWL_MEM, null );
    
    /** <p>The namespace of the vocabulary as a string</p> */
    public static final String NS = "http://www.jade-hs.de/RDF/Ontology#";
    
    /** <p>The namespace of the vocabulary as a string</p>
     *  @see #NS */
    public static String getURI() {return NS;}
    
    /** <p>The namespace of the vocabulary as a resource</p> */
    public static final Resource NAMESPACE = m_model.createResource( NS );
    
    /** <p>The ontology's owl:versionInfo as a string</p> */
    public static final String VERSION_INFO = "v0.1";
    
    public static final ObjectProperty hatFreund = m_model.createObjectProperty( "http://www.jade-hs.de/RDF/Ontology#hatFreund" );
    
    public static final OntClass Frau = m_model.createClass( "http://www.jade-hs.de/RDF/Ontology#Frau" );
    
    public static final OntClass Mann = m_model.createClass( "http://www.jade-hs.de/RDF/Ontology#Mann" );
    
    public static final OntClass Mensch = m_model.createClass( "http://www.jade-hs.de/RDF/Ontology#Mensch" );
    
    public static final OntClass Person = m_model.createClass( "http://www.jade-hs.de/RDF/Ontology#Person" );
    
}
